FROM amazonlinux
WORKDIR /root
RUN yum install tar gzip -y
COPY . .
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash \
  && . .nvm/nvm.sh \
  && nvm install 8.10.0 \
  && npm install -g serverless \
  && npm install

EXPOSE 3000
CMD . .nvm/nvm.sh \
  && sls offline start